# Generated by Django 3.1.7 on 2021-07-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyuser'),
        ('dashboard', '0002_internshipinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('placement_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.placementinfo')),
                ('student_username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Student_internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('internship_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.internshipinfo')),
                ('student_username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentuser')),
            ],
        ),
    ]
