# Generated by Django 3.2.5 on 2021-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210728_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipinfo',
            name='regform_link',
            field=models.URLField(default='https://forms.gle/VNgHt2XeRaDn65Wv6'),
        ),
        migrations.AlterField(
            model_name='placementinfo',
            name='regform_link',
            field=models.URLField(default='https://forms.gle/VNgHt2XeRaDn65Wv6'),
        ),
    ]
