# Generated by Django 3.1.7 on 2021-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210814_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipinfo',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='placementinfo',
            name='pending',
        ),
        migrations.AddField(
            model_name='student_internship',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_placement',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internshipinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placementinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_internship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_placement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
