# Generated by Django 3.1.7 on 2021-07-14 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(default='', max_length=255)),
                ('branch', models.CharField(default='', max_length=255)),
                ('yog', models.IntegerField(default=0)),
                ('contact', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
