# Generated by Django 3.1.7 on 2021-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
