# Generated by Django 3.2.5 on 2021-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210728_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='stuImage',
            field=models.ImageField(default='static/images/user_profile1.png', null=True, upload_to='Images/'),
        ),
    ]
