# Generated by Django 3.2.5 on 2021-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_companyuser_comimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='stuImage',
            field=models.ImageField(default='static/images/user_profile1.png', null=True, upload_to='Images/'),
        ),
    ]
