# Generated by Django 3.2.5 on 2021-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentuser_stuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='comImage',
            field=models.ImageField(default='Images/user_profile1.png', null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='stuImage',
            field=models.ImageField(default='Images/user_profile1.png', null=True, upload_to='Images/'),
        ),
    ]
